/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventiIndexRouteImport } from './routes/eventi/index'
import { Route as EventiEventoIdRouteImport } from './routes/eventi/$eventoId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiIndexRoute = EventiIndexRouteImport.update({
  id: '/eventi/',
  path: '/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiEventoIdRoute = EventiEventoIdRouteImport.update({
  id: '/eventi/$eventoId',
  path: '/eventi/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi': typeof EventiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi': typeof EventiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi/': typeof EventiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/eventi/$eventoId' | '/eventi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/eventi/$eventoId' | '/eventi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/eventi/$eventoId'
    | '/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventiEventoIdRoute: typeof EventiEventoIdRoute
  EventiIndexRoute: typeof EventiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/': {
      id: '/eventi/'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/$eventoId': {
      id: '/eventi/$eventoId'
      path: '/eventi/$eventoId'
      fullPath: '/eventi/$eventoId'
      preLoaderRoute: typeof EventiEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventiEventoIdRoute: EventiEventoIdRoute,
  EventiIndexRoute: EventiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
