/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventiIndexRouteImport } from './routes/eventi/index'
import { Route as EventiGestioneRouteImport } from './routes/eventi/gestione'
import { Route as EventiEventoIdRouteImport } from './routes/eventi/$eventoId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiIndexRoute = EventiIndexRouteImport.update({
  id: '/eventi/',
  path: '/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiGestioneRoute = EventiGestioneRouteImport.update({
  id: '/eventi/gestione',
  path: '/eventi/gestione',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiEventoIdRoute = EventiEventoIdRouteImport.update({
  id: '/eventi/$eventoId',
  path: '/eventi/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi/gestione': typeof EventiGestioneRoute
  '/eventi': typeof EventiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi/gestione': typeof EventiGestioneRoute
  '/eventi': typeof EventiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/eventi/$eventoId': typeof EventiEventoIdRoute
  '/eventi/gestione': typeof EventiGestioneRoute
  '/eventi/': typeof EventiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/eventi/$eventoId'
    | '/eventi/gestione'
    | '/dashboard'
    | '/eventi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/eventi/gestione'
    | '/dashboard'
    | '/eventi/$eventoId'
    | '/eventi'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/eventi/gestione'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/eventi/$eventoId'
    | '/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventiEventoIdRoute: typeof EventiEventoIdRoute
  EventiGestioneRoute: typeof EventiGestioneRoute
  EventiIndexRoute: typeof EventiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/': {
      id: '/eventi/'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/gestione': {
      id: '/eventi/gestione'
      path: '/eventi/gestione'
      fullPath: '/eventi/gestione'
      preLoaderRoute: typeof EventiGestioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/$eventoId': {
      id: '/eventi/$eventoId'
      path: '/eventi/$eventoId'
      fullPath: '/eventi/$eventoId'
      preLoaderRoute: typeof EventiEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventiEventoIdRoute: EventiEventoIdRoute,
  EventiGestioneRoute: EventiGestioneRoute,
  EventiIndexRoute: EventiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
